### ISSUE TITLE
500 errors

### ISSUE THREAD

**Issue by kaledev** [v411e/hype#7]
Is this project still active / working? Tried it out and although it works occasionally (may boost a few a day), it more often than not fails with a `('Mastodon API returned error', 500, 'Internal Server Error', None)` error after the first try on an instance.

**Comment by kaledev** [comment]
Nevermind! - error in my server. My /public/system directory briefly had the wrong owner/group after an upgrade - I thought the 500 errors were the API but it looks like it was an error related to my directory instead.

**Comment by v411e** [comment]
This project is still active and should work. I am glad you found the issue :)
