### ISSUE TITLE
Hype’s Licence?

### ISSUE THREAD

**Issue by hapeho** [v411e/hype#8]
Under which licence is `hype` published? I’ve seen a few public forks, would have some modifications for my own use case and wonder whether I could use the code freely as a base for it.

**Comment by tante** [comment]
That is a good question. Let's see what the original author will put it under (weird that I didn't check, I am usually better with that).
I'd personally GPL it but it obviously depends on the original. Other bots the author wrote are MIT so it might end up like that.

**Comment by v411e** [comment]
Hi, this is a good question. I thought about it and will create an AGPLv3 license for the project, because I like the idea of copyleft. :)

**Comment by v411e** [comment]
Feel free to submit your modifications as a PR to this repository :)
